In [1]:
import numpy as np

In [3]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [5]:
type(a[0])

numpy.float64

In [6]:
a.shape

(5,)

In [8]:
a.shape=(5,1)

In [9]:
a

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [11]:
z=np.ones(10)

In [14]:
z.shape=(10,1)
z

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [15]:
z=np.linspace(2,10,5)### From 2 to 10 with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

In [16]:
## list to array
a_list=[2,3,4,5,6,8,9]
z=np.array(a_list)
z

array([2, 3, 4, 5, 6, 8, 9])

In [17]:
z.shape

(7,)

In [44]:
b_list=[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]]
z=np.array(b_list)
z

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
z.shape ## 2 row 7 column

(2, 7)

In [20]:
z=np.array([b_list])
z

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]])

In [21]:
z.shape

(1, 2, 7)

In [22]:
## random number
np.random.seed(0)
z1=np.random.randint(10,size=6) ##maxium 10,sie 6
z1

array([5, 0, 3, 3, 7, 9])

In [23]:
z1[0:3]

array([5, 0, 3])

## Accessing Specific Elements- Columns- Rows, etc.

In [46]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a.shape

(2, 6)

In [26]:
a.ndim

2

In [27]:
a.nbytes

48

In [28]:
#Get specific column
a[0,2]

3

In [29]:
#Get a specific row
a[1,:]

array([ 7,  8,  9, 10, 11, 12])

In [36]:
a[1,0:-1:2]#-1 exclusive,2 step size


array([7, 9])

### 3D Array

In [37]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b.shape ## en dıstaki koseli parantezi sayma gibi

(2, 2, 2)

In [38]:
b[0,1,1]

4

In [39]:
b[1,1,1]

8

In [40]:
#
b[:,1,:]=[[8,8],[9,9]] #hepsiin 1.indexine git ordaki butun array'i degistir
b

array([[[1, 2],
        [8, 8]],

       [[5, 6],
        [9, 9]]])

### Initializing Different Types of Arrays

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [43]:
## Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [50]:
## Any other number(full_like)
np.full_like(a,99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [51]:
#Random decimal numbers (0-1)
np.random.rand(4,2,3) #4tane-2row-3column boyutunda

array([[[0.6235637 , 0.38438171, 0.29753461],
        [0.05671298, 0.27265629, 0.47766512]],

       [[0.81216873, 0.47997717, 0.3927848 ],
        [0.83607876, 0.33739616, 0.64817187]],

       [[0.36824154, 0.95715516, 0.14035078],
        [0.87008726, 0.47360805, 0.80091075]],

       [[0.52047748, 0.67887953, 0.72063265],
        [0.58201979, 0.53737323, 0.75861562]]])

In [53]:
## Random Integer Values
np.random.randint(2,6,size=(3,3))

array([[4, 2, 2],
       [2, 3, 3],
       [4, 2, 2]])

In [58]:
arr=np.array([[1,2,3,4]])
r1=arr.repeat(4 ,axis=0)
r2=arr.repeat(4,axis=1)
r1


array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [59]:
r2

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]])

In [61]:
output=np.ones((5,5)) ##shape=5-5
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Copy issue - Careful

In [62]:
## a ve b same object gibi davranıyorlar
a=np.array([1,2,3])
b=a
b[0]=100
print(a)

[100   2   3]


In [63]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


# Mathematics

In [64]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [65]:
a+4

array([5, 6, 7, 8])

In [66]:
a*2

array([2, 4, 6, 8])

In [67]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [68]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

- 
### Lınear Algebra